server:
  port: 9770

spring:
  redis:
    key-prefix: dev  # redis key的前缀， 环境的多个实例一定要配置一样（即prod1和prod2文件中需要配置一致）
  rabbitmq:
      host: localhost
      port: 5672
      password: admin
      username: admin
  redis:
    host: localhost
    port: 6379
    password: Bee@9394
    pool:
      max-active: 20
      min-idle: 2
      max-idle: 8
      max-wait: 100
    key-prefix: dev
  sleuth:
    sampler:
      percentage: 1
    integration:
      enabled: false
    scheduled:
      skip-pattern: "^org.*HystrixStreamTask$"
  zipkin:
#    base-url: http://BeeExpress-zipkin:8510
    locator:
      discovery:
        enabled: true
    service:
      name: ${spring.application.name}


# rabbitMQ/Mysql/Redis ip，端口，帐号等根据环境自行修改。